Battle_SetTurnInfo(BATTLE_TURN.TIME,-1) //设置回合属性

Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,70)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,70)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,70)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,70)